
var commands = module.exports.commands = [
  'getbestblockhash',
  'getblock',
  'getblockchaininfo',
  'getblockcount',
  'getblockhash',
  'getblockheader',
  'getchaintips',
  'getchaintxstats',
  'getdifficulty',
  'getmempoolancestors',
  'getmempooldescendants',
  'getmempoolentry',
  'getmempoolinfo',
  'getrawmempool',
  'gettxout',
  'gettxoutproof',
  'gettxoutsetinfo',
  'preciousblock',
  'pruneblockchain',
  'savemempool',
  'verifychain',
  'verifytxoutproof',

  'getmemoryinfo',
  'help',
  'logging',
  'stop',
  'uptime',

  'generate',
  'generatetoaddress',

  'getblocktemplate',
  'getmininginfo',
  'getnetworkhashps',
  'prioritisetransaction',
  'submitblock',

  'addnode',
  'clearbanned',
  'disconnectnode',
  'getaddednodeinfo',
  'getconnectioncount',
  'getnettotals',
  'getnetworkinfo',
  'getpeerinfo',
  'listbanned',
  'ping',
  'setban',
  'setnetworkactive',

  'combinerawtransaction',
  'createrawtransaction',
  'decoderawtransaction',
  'decodescript',
  'fundrawtransaction',
  'getrawtransaction',
  'sendrawtransaction',
  'signrawtransaction',

  'createmultisig',
  'estimatefee',
  'estimatesmartfee',
  'signmessagewithprivkey',
  'validateaddress',
  'verifymessage',

  'abandontransaction',
  'abortrescan',
  'addmultisigaddress',
  'backupwallet',
  'bumpfee',
  'dumpprivkey',
  'dumpwallet',
  'encryptwallet',
  'getaccount',
  'getaccountaddress',
  'getaddressesbyaccount',
  'getbalance',
  'getnewaddress',
  'getrawchangeaddress',
  'getreceivedbyaccount',
  'getreceivedbyaddress',
  'gettransaction',
  'getunconfirmedbalance',
  'getwalletinfo',
  'importaddress',
  'importmulti',
  'importprivkey',
  'importprunedfunds',
  'importpubkey',
  'importwallet',
  'keypoolrefill',
  'listaccounts',
  'listaddressgroupings',
  'listlockunspent',
  'listreceivedbyaccount',
  'listreceivedbyaddress',
  'listsinceblock',
  'listtransactions',
  'listunspent',
  'listwallets',
  'lockunspent',
  'move',
  'removeprunedfunds',
  'rescanblockchain',
  'sendfrom',
  'sendmany',
  'replaceable',
  'sendtoaddress',
  'replaceable',
  'setaccount',
  'settxfee',
  'signmessage',
  'walletlock',
  'walletpassphrase',
  'walletpassphrasechange'
]

module.exports.isCommand = function(command) {
  command = command.toLowerCase()
  for (var i=0, len=commands.length ;i<len; i++) {
    if (commands[i].toLowerCase() === command) {
        return true
    }
  }
}
